
create table os_users (
    user_id             number generated by default as identity not null enable,
    username            varchar2(100 byte) not null enable,
    display_name        varchar2(255 byte),
    email               varchar2(320 byte),
    password_hash       raw(32),
    password_salt       raw(32),
    password_iterations number default 10000,
    is_active           varchar2(1 byte) default 'Y' not null enable,
    created_at          timestamp(6) default systimestamp not null enable,
    updated_at          timestamp(6),
    last_login_at       timestamp(6),
    password_changed_at timestamp(6)
);

alter table os_users add constraint os_users_email_uk unique ( email )
    using index enable;

alter table os_users
    add constraint os_users_is_active_ck
        check ( is_active in ( 'Y', 'N' ) ) enable;

alter table os_users
    add constraint os_users_pk primary key ( user_id )
        using index enable;

alter table os_users add constraint os_users_username_uk unique ( username )
    using index enable;


create table os_auth_challenges (
    challenge_id    raw(32) not null enable,
    user_id         number,
    username        varchar2(100 byte),
    challenge_type  varchar2(20 byte) not null enable,
    challenge_value raw(32) not null enable,
    origin          varchar2(500 byte),
    rp_id           varchar2(255 byte),
    session_id      varchar2(100 byte),
    ip_address      varchar2(45 byte),
    created_at      timestamp(6) default systimestamp,
    expires_at      timestamp(6) not null enable,
    used_at         timestamp(6)
);

alter table os_auth_challenges
    add constraint os_auth_challenges_pk primary key ( challenge_id )
        using index enable;

alter table os_auth_challenges
    add constraint os_auth_challenges_type_ck
        check ( challenge_type in ( 'REGISTRATION', 'AUTHENTICATION' ) ) enable;


create table os_auth_credentials (
    credential_id          raw(1024),
    user_id                number not null enable,
    public_key_x           raw(32),
    public_key_y           raw(32),
    public_key_algorithm   number default - 7,
    sign_count             number default 0,
    credential_name        varchar2(255 byte),
    credential_device_type varchar2(50 byte),
    aaguid                 raw(16),
    transports             varchar2(500 byte),
    attestation_fmt        varchar2(50 byte),
    attestation_data       blob,
    is_active              varchar2(1 byte) default 'Y',
    created_at             timestamp(6) default systimestamp,
    last_used_at           timestamp(6)
);

create unique index os_auth_credentials_pk on
    os_auth_credentials (
        credential_id
    );

alter table os_auth_credentials
    add constraint os_auth_credentials_pk
        primary key ( credential_id )
            using index os_auth_credentials_pk enable;

alter table os_auth_credentials
    add constraint os_auth_cred_active_ck
        check ( is_active in ( 'Y', 'N' ) ) enable;


create table os_auth_audit_log (
    audit_id      raw(32) default sys_guid(),
    event_type    varchar2(50 byte) not null enable,
    user_id       number,
    credential_id raw(1024),
    success       varchar2(1 byte) default 'Y',
    ip_address    varchar2(45 byte),
    session_id    varchar2(100 byte),
    error_message varchar2(4000 byte),
    created_at    timestamp(6) default systimestamp
);

alter table os_auth_audit_log
    add constraint os_auth_audit_log_pk primary key ( audit_id )
        using index enable;

alter table os_auth_audit_log
    add constraint os_auth_audit_success_ck
        check ( success in ( 'Y', 'N' ) ) enable;
